name: xeus-python-kernel
channels:
  - https://conda.anaconda.org/michaelweinold/label/emscripten
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge

dependencies:
  - xeus-python
  - ipycanvas
  - test_wasm_platform_specific_dependencies